### ISSUE TITLE
默认启动时，加载的软件包不兼容

### ISSUE THREAD

**Issue by zzjjbb** [rxrw/mirai-docker-starter#1]
未做自定义配置时，加载的mirai-api-http为v1.11.0，该版本过旧，与自动加载的其他模块不兼容，会报错`java.lang.NoSuchMethodError: 'double kotlin.time.DurationKt.toDuration(int, java.util.concurrent.TimeUnit)'`

我自己尝试手动替换成1.12或者2.x就可以正常运行了，如果大佬有时间希望可以把DockerHub的镜像也修复一下，多谢！

**Comment by zzjjbb** [comment]
或者我建议可以固定一套能用的版本配置，不要只自动更新部分软件包导致依赖破坏

**Comment by rxrw** [comment]
好，可以直接pr，要我周一弄一下

**Comment by bldq** [comment]
请问树莓派4B（arm架构，aarch64的机器）可以支持吗？

**Comment by rxrw** [comment]
理论上支持的

发自我的iPhone

**Comment by rxrw** [comment]
ffixedd
