### ISSUE TITLE
Docker部署成功后telnet连接闪退，websocket无法连接

### ISSUE THREAD

**Issue by NextSeconds** [rxrw/mirai-docker-starter#2]
过程：
docker run -d --name mirai -p 8081:8080 -v /volume1/docker/mirai/config:/app/config -v /volume1/docker/mirai/plugins:/app/plugins reprover/mirai-http:latest 
放到8081跑了，然后把autologin配置好，Plugins里面放了mirai-api-http-v2.2.0.mirai.jar
然后启动的时候都提示插件加载了，同时聊天消息也正常了
![1](https://user-images.githubusercontent.com/35531612/131626879-ed4e05c1-a4b7-429b-8cc8-d26de783b693.jpg)
但是ws连接测试失败，使用的连接：ws://localhost:8081/message?verifyKey=INITKEYTZVLEdkX&qq=1743797837
![2](https://user-images.githubusercontent.com/35531612/131626899-d0b3116a-4fe0-43c7-958d-02178e854fb7.jpg)

**Comment by rxrw** [comment]
![131626879-ed4e05c1-a4b7-429b-8cc8-d26de783b693](https://user-images.githubusercontent.com/9566402/131628729-e404bfb4-2c3b-4db3-ad46-8149686147b9.png)
监听在容器内部吧

**Comment by NextSeconds** [comment]
> ![131626879-ed4e05c1-a4b7-429b-8cc8-d26de783b693](https://user-images.githubusercontent.com/9566402/131628729-e404bfb4-2c3b-4db3-ad46-8149686147b9.png)
> 监听在容器内部吧

容器内部。。没太明白您的意思。。我需要怎么做呢

刚刚我重新部署了一个
docker run -d --name mirai -p 8080:8080 -v /d/mirai/config:/app/config -v /d/mirai/plugins:/app/plugins reprover/mirai-http:latest 
这次内外端口一致，避免端口歧义
但是依然使用下面的无法建立websocket连接
ws://localhost:8080/message?verifyKey=INITKEYTZVLEdkX&qq=1743797837
![3](https://user-images.githubusercontent.com/35531612/131630287-39cfd048-676d-4290-9b60-53d344fe9a31.jpg)

**Comment by rxrw** [comment]
在docker内部的网络，是独立的网络空间，程序运行在容器里，监听的是他本地的ip

在mirai的配置里把监听的host改成0.0.0.0，应该就好了

**Comment by NextSeconds** [comment]
> 在docker内部的网络，是独立的网络空间，程序运行在容器里，监听的是他本地的ip
> 
> 在mirai的配置里把监听的host改成0.0.0.0，应该就好了

感谢！可以了！
